#!/usr/bin/env ansible-playbook
---
# Testing automatic scaling up of instances
# ansible-playbook -v -i `ir workspace inventory` test_autoscaling_up.yaml

- hosts: undercloud
  become: no
  name: Test autoscaling
  tasks:

    - name: register instance IP address
      shell: |
        source ~/overcloudrc;
        openstack server show controller-1 -f value -c addresses | sed 's/ctlplane=//g';
      register: instance1

    - name: Test automatic scaling up of instances
      shell: |
        ssh -i ~/mykey.pem cirros@{{ instance1.stdout }} "sudo dd if=/dev/zero of=/dev/null &"
      register: result
      failed_when: result.rc >= 1

    - name: Verify that the alarm has been triggered
      shell: |
        source ~/overcloudrc;
        openstack alarm list;
      register: result
      failed_when: '"alarm" not in result.stdout'

    - name: Wait for 60 sec
      pause:
        minutes: 1

    - name: Verify that the Orchestration starts another instance
      shell: |
        source ~/overcloudrc;
        openstack server list;
      register: result
      failed_when: '"ACTIVE" not in result.stdout'
    
    - name: Wait for 60 sec
      pause:
        minutes: 1

    - name: Verify that the Orchestration service has autoscaled to three instances
      shell: |
        source ~/overcloudrc;
        openstack server list;
      register: result
      failed_when: '"ACTIVE" not in result.stdout'

...