#!/usr/bin/env ansible-playbook
---
- hosts: undercloud
  become: no
  name: Test autoscaling
  tasks:

    - name: register instance IP address
      shell: |
        source ~/overcloudrc;
        openstack server show controller-1 -f value -c addresses | sed 's/ctlplane=//g';
      register: instance1

    - name: Test automatic scaling up of instances
      shell: |
        ssh -i ~/mykey.pem cirros@{{ instance1.stdout }} "sudo killall dd"
      register: result
      failed_when: result.rc >= 1

    - name: Verify that the alarm has been triggered
      shell: |
        source ~/stackrc;
        openstack alarm list;
      register: result
      failed_when: '"alarm" not in result.stdout'

    - name: Wait for 60 sec
      pause:
        minutes: 1

    - name: Orchestration continually reduce the number of instances
      shell: |
        source ~/overcloudrc;
        openstack server list;
      register: result
      failed_when: '"ACTIVE" not in result.stdout'
